name: ReleaseApp
on:
  workflow_run:
    workflows: [BuildApp]
    types:
        - completed
jobs:
    Release-Project:
        name: Release project
        runs-on: ubuntu-latest
        needs: build-project
        permissions:
            contents: write
        steps:
            - name: Download Site Content
              uses: actions/download-artifact@v4
              with:
                name: static-site
            - name: view contents of static-site
              run: ls -R
            - name: Archive(zip) the contents of the built artifact
              uses: thedoctor0/zip-release@0.7.5
              with:
                type: 'zip'
                filename: 'static.zip'
            - name: Create GitHub Release
              id: create_new_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.run_number}}
                release_name: Release ${{ github.run_number}}
            - name: upload release asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_new_release.outputs.upload_url }}
                asset_path: ./static.zip
                asset_name: site-v${{ github.run_number }}.zip
                asset_content_type: application/zip
